// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_option = require("bs-platform/lib/js/js_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Login$WhatDidIEat = require("./Login.bs.js");

var component = ReasonReact.reducerComponent("App");

function make(token, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function () {
              console.log("token: ", Js_option.getWithDefault("No token", token));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* loginStatus */0];
              return React.createElement("div", undefined, match ? React.createElement("div", undefined, "Logged in: " + match[0]) : ReasonReact.element(/* None */0, /* None */0, Login$WhatDidIEat.make((function (token) {
                                      return Curry._1(self[/* send */3], /* Login */[token]);
                                    }), /* array */[])));
            }),
          /* initialState */(function () {
              return /* record */[/* loginStatus : NotLoggedIn */0];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              if (action) {
                return /* Update */Block.__(0, [/* record */[/* loginStatus : LoggedIn */[action[0]]]]);
              } else {
                return /* Update */Block.__(0, [/* record */[/* loginStatus : NotLoggedIn */0]]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
