// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Auth = require("aws-amplify/lib/Auth");

function authData(username, password) {
  return {
          Username: username,
          Password: password
        };
}

var Cognito = /* module */[/* authData */authData];

function configure(identityPoolId, region, userPoolId, userPoolWebClientId) {
  Auth.default.configure({
        Auth: {
          identityPoolId: identityPoolId,
          region: region,
          userPoolId: userPoolId,
          userPoolWebClientId: userPoolWebClientId
        }
      });
  return /* () */0;
}

function signIn(username, password) {
  return Auth.default.signIn(username, password).then((function (result) {
                console.log(result);
                var challengeName = result.challengeName;
                return Promise.resolve((challengeName == null) ? (console.log("no challenge"), /* LoginSuccessful */Block.__(0, [result])) : (console.log("Challenge", challengeName), /* LoginChallenge */Block.__(2, [challengeName])));
              }));
}

function changePassword(oldPassword, newPassword, user) {
  return Auth.changePassword(user, oldPassword, newPassword);
}

var Amplify = /* module */[
  /* configure */configure,
  /* signIn */signIn,
  /* changePassword */changePassword
];

exports.Cognito = Cognito;
exports.Amplify = Amplify;
/* aws-amplify/lib/Auth Not a pure module */
