// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var App$WhatDidIEat = require("./App.bs.js");
var Aws$WhatDidIEat = require("./Aws.bs.js");
var Util$WhatDidIEat = require("./Util.bs.js");

var token = localStorage.getItem("token");

var token$1 = (token == null) ? /* None */0 : [token];

Aws$WhatDidIEat.Amplify[/* configure */0](Util$WhatDidIEat.Env[/* get */0]("IDENTITY_POOL_ID"), Util$WhatDidIEat.Env[/* get */0]("REGION"), Util$WhatDidIEat.Env[/* get */0]("USER_POOL_ID"), Util$WhatDidIEat.Env[/* get */0]("USER_POOL_WEB_CLIENT_ID"));

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$WhatDidIEat.make(token$1, /* array */[])), "app");

console.log("POOL ID", Util$WhatDidIEat.Env[/* get */0]("IDENTITY_POOL_ID"));

exports.token = token$1;
/* token Not a pure module */
