service: whatdidieat-graphql

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["entitiesTable", "Arn"] }
        - {
            "Fn::Join":
              [
                "/",
                [{ "Fn::GetAtt": ["entitiesTable", "Arn"] }, "index", "GSI1"],
              ],
          }
  environment:
    REGION: "${self:provider.region}"
    STAGE: "${self:provider.stage}"

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      seed: true
    seed:
      db:
        sources:
          - table: ${self:provider.environment.DYNAMODB_TABLE}
            sources: [./seedDb/db.json]

package:
  include: handler.ts

functions:
  query:
    handler: src/handler.query
    events:
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: graphql
          method: post
          cors: true

resources:
  Resources:
    userPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}
    entitiesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: data
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: sk
                KeyType: HASH
              - AttributeName: data
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
