// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var AwsSdk = require("aws-sdk");

function update(region, endpoint) {
  AwsSdk.config.update({
        region: region,
        endpoint: endpoint
      });
  return /* () */0;
}

function get(table, key, client) {
  return new Promise((function (resolve, reject) {
                client.get({
                      TableName: table,
                      Key: key
                    }, (function (error, data) {
                        if (error !== null) {
                          return reject(error);
                        } else {
                          console.log("completed dynamodb get");
                          console.log("Data", data);
                          return resolve(data);
                        }
                      }));
                return /* () */0;
              }));
}

function scan($staropt$star, table, client) {
  var limit = $staropt$star ? $staropt$star[0] : 100;
  return new Promise((function (resolve, reject) {
                client.scan({
                      TableName: table,
                      Limit: limit
                    }, (function (error, data) {
                        if (error !== null) {
                          return reject(error);
                        } else {
                          console.log("completed dynamodb scan");
                          return resolve(data);
                        }
                      }));
                return /* () */0;
              }));
}

var DynamoDb = /* module */[
  /* get */get,
  /* scan */scan
];

exports.update = update;
exports.DynamoDb = DynamoDb;
/* aws-sdk Not a pure module */
