// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var AwsSdk = require("aws-sdk");
var AwsLambda = require("@ahrefs/bs-aws-lambda/lib/js/src/awsLambda.bs.js");
var Js_option = require("bs-platform/lib/js/js_option.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function update(region, endpoint) {
  AwsSdk.config.update({
        region: region,
        endpoint: endpoint
      });
  return /* () */0;
}

function get(table, key, client) {
  return new Promise((function (resolve, reject) {
                client.get({
                      TableName: table,
                      Key: key
                    }, (function (error, data) {
                        if (error !== null) {
                          return reject(error);
                        } else {
                          console.log("completed dynamodb get");
                          console.log("Data", data);
                          return resolve(data);
                        }
                      }));
                return /* () */0;
              }));
}

function scan($staropt$star, table, client) {
  var limit = $staropt$star ? $staropt$star[0] : 100;
  return new Promise((function (resolve, reject) {
                client.scan({
                      TableName: table,
                      Limit: limit
                    }, (function (error, data) {
                        if (error !== null) {
                          return reject(error);
                        } else {
                          console.log("completed dynamodb scan");
                          return resolve(data);
                        }
                      }));
                return /* () */0;
              }));
}

var DynamoDb = /* module */[
  /* get */get,
  /* scan */scan
];

function okResult(body) {
  return AwsLambda.APIGatewayProxy[/* result */0](/* None */0, /* `Plain */[
              -675583510,
              JSON.stringify(body)
            ], 200, /* () */0);
}

function errorResult($staropt$star, requestId, message) {
  var statusCode = $staropt$star ? $staropt$star[0] : 500;
  return AwsLambda.APIGatewayProxy[/* result */0](/* None */0, /* `Plain */[
              -675583510,
              JSON.stringify({
                    message: message,
                    requestId: Js_null_undefined.fromOption(requestId)
                  })
            ], statusCode, /* () */0);
}

function queryStringParam($$event, paramName) {
  return Js_option.andThen((function (queryString) {
                return Js_primitive.undefined_to_opt(queryString[paramName]);
              }), Js_primitive.null_to_opt($$event.queryStringParameters));
}

update("us-east-2", "http://localhost:8000");

exports.update = update;
exports.DynamoDb = DynamoDb;
exports.okResult = okResult;
exports.errorResult = errorResult;
exports.queryStringParam = queryStringParam;
/*  Not a pure module */
