// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var V1 = require("uuid/v1");

function createUser(name) {
  var uuid = V1({
        msecs: 1
      });
  return /* record */[
          /* id */uuid.toString(),
          /* createdDate */"",
          /* name */name,
          /* email */"",
          /* password */""
        ];
}

function hello($$event, _, callback) {
  var match = $$event.body;
  var body = match !== null ? match : "";
  var response = {
    statusCode: 200,
    body: JSON.stringify(body),
    headers: null,
    isBase64Encoded: $$event.isBase64Encoded
  };
  Curry._2(callback, null, response);
  return Promise.resolve(/* () */0);
}

var UuidV1 = 0;

exports.UuidV1 = UuidV1;
exports.createUser = createUser;
exports.hello = hello;
/* uuid/v1 Not a pure module */
